project_id = "rfwrsqjanuelmzmttrbe"

[functions.track-request]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.admin-verify]
verify_jwt = false

[functions.admin-requests]
verify_jwt = false

[functions.admin-logout]
verify_jwt = false

[functions.site-content]
verify_jwt = false

[functions.check-availability]
verify_jwt = false

[functions.reschedule-request]
verify_jwt = false
